theme: minima
url: https://equationoftime.tech
author:
  name: John Todd
  email: jqt3of5@gmail.com
description: >
  A place to discuss and unpack the various philosophies surrounding software testing and software development. An Equation of Time for the modern age. 

